archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make tfgen
builds:
  - binary: pulumi-resource-jetstream
    dir: provider
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ignore: []
    ldflags:
      - -X github.com/Triple-Whale/pulumi-jetstream/provider/pkg/version.Version={{.Tag}}
    main: ./cmd/pulumi-resource-jetstream/
release:
  disable: false
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
