# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

credentialData: Optional[str]
"""
The contents of the NATS 2.0 Credentials file to use
"""

credentials: Optional[str]
"""
Path to the NATS 2.0 credentials file to use for authentication
"""

nkey: Optional[str]
"""
Connect using a NKEY seed stored in a file
"""

password: Optional[str]
"""
Connect using a password
"""

servers: Optional[str]
"""
Comma separated list of NATS servers to connect to
"""

tls: Optional[str]

user: Optional[str]
"""
Connect using an username, used as token when no password is given
"""

