# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .consumer import *
from .kv_bucket import *
from .kv_entry import *
from .provider import *
from .stream import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_jetstream.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_jetstream.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "jetstream",
  "mod": "index/consumer",
  "fqn": "pulumi_jetstream",
  "classes": {
   "jetstream:index/consumer:Consumer": "Consumer"
  }
 },
 {
  "pkg": "jetstream",
  "mod": "index/kvBucket",
  "fqn": "pulumi_jetstream",
  "classes": {
   "jetstream:index/kvBucket:KvBucket": "KvBucket"
  }
 },
 {
  "pkg": "jetstream",
  "mod": "index/kvEntry",
  "fqn": "pulumi_jetstream",
  "classes": {
   "jetstream:index/kvEntry:KvEntry": "KvEntry"
  }
 },
 {
  "pkg": "jetstream",
  "mod": "index/stream",
  "fqn": "pulumi_jetstream",
  "classes": {
   "jetstream:index/stream:Stream": "Stream"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "jetstream",
  "token": "pulumi:providers:jetstream",
  "fqn": "pulumi_jetstream",
  "class": "Provider"
 }
]
"""
)
