// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package jetstream

import (
	"fmt"

	"github.com/Triple-Whale/pulumi-jetstream/sdk/go/jetstream/internal"
	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "jetstream:index/consumer:Consumer":
		r = &Consumer{}
	case "jetstream:index/kvBucket:KvBucket":
		r = &KvBucket{}
	case "jetstream:index/kvEntry:KvEntry":
		r = &KvEntry{}
	case "jetstream:index/stream:Stream":
		r = &Stream{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:jetstream" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"jetstream",
		"index/consumer",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"jetstream",
		"index/kvBucket",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"jetstream",
		"index/kvEntry",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"jetstream",
		"index/stream",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"jetstream",
		&pkg{version},
	)
}
