// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Jetstream.Outputs
{

    [OutputType]
    public sealed class StreamSourceExternal
    {
        /// <summary>
        /// The subject prefix for the remote API
        /// </summary>
        public readonly string? Api;
        /// <summary>
        /// The subject prefix where messages will be delivered to
        /// </summary>
        public readonly string? Deliver;

        [OutputConstructor]
        private StreamSourceExternal(
            string? api,

            string? deliver)
        {
            Api = api;
            Deliver = deliver;
        }
    }
}
