// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Jetstream.Outputs
{

    [OutputType]
    public sealed class StreamMirror
    {
        /// <summary>
        /// Streams replicated from other accounts
        /// </summary>
        public readonly Outputs.StreamMirrorExternal? External;
        /// <summary>
        /// Only copy messages matching a specific subject, not usable for mirrors
        /// </summary>
        public readonly string? FilterSubject;
        /// <summary>
        /// The name of the source Stream
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The sequence to start mirroring from
        /// </summary>
        public readonly int? StartSeq;
        /// <summary>
        /// The time stamp in the source stream to start from, in RFC3339 format
        /// </summary>
        public readonly string? StartTime;
        /// <summary>
        /// The subject filtering sources and associated destination transforms
        /// </summary>
        public readonly ImmutableArray<Outputs.StreamMirrorSubjectTransform> SubjectTransforms;

        [OutputConstructor]
        private StreamMirror(
            Outputs.StreamMirrorExternal? external,

            string? filterSubject,

            string name,

            int? startSeq,

            string? startTime,

            ImmutableArray<Outputs.StreamMirrorSubjectTransform> subjectTransforms)
        {
            External = external;
            FilterSubject = filterSubject;
            Name = name;
            StartSeq = startSeq;
            StartTime = startTime;
            SubjectTransforms = subjectTransforms;
        }
    }
}
