// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/Triple-Whale/pulumi-jetstream/sdk/go/jetstream/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The contents of the NATS 2.0 Credentials file to use
func GetCredentialData(ctx *pulumi.Context) string {
	return config.Get(ctx, "jetstream:credentialData")
}

// Path to the NATS 2.0 credentials file to use for authentication
func GetCredentials(ctx *pulumi.Context) string {
	return config.Get(ctx, "jetstream:credentials")
}

// Connect using a NKEY seed stored in a file
func GetNkey(ctx *pulumi.Context) string {
	return config.Get(ctx, "jetstream:nkey")
}

// Connect using a password
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "jetstream:password")
}

// Comma separated list of NATS servers to connect to
func GetServers(ctx *pulumi.Context) string {
	return config.Get(ctx, "jetstream:servers")
}
func GetTls(ctx *pulumi.Context) string {
	return config.Get(ctx, "jetstream:tls")
}

// Connect using an username, used as token when no password is given
func GetUser(ctx *pulumi.Context) string {
	return config.Get(ctx, "jetstream:user")
}
