// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"github.com/Triple-Whale/pulumi-jetstream/sdk/go/jetstream/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type Tls struct {
	// Path to the server root CA file (in PEM format). Needed when the NATS server has TLS enabled with an unknown root CA
	CaFile *string `pulumi:"caFile"`
	// The root CA (file) content, in PEM format. Needed when the NATS server has TLS enabled with an unknown root CA
	CaFileData *string `pulumi:"caFileData"`
	// Path to client cert file (in PEM format). Needed when NATS server is configured to verify client certificate
	CertFile *string `pulumi:"certFile"`
	// The cert file content (in PEM format). Needed when NATS server is configured to verify client certificate
	CertFileData *string `pulumi:"certFileData"`
	// Path to client key file (in PEM format). Needed when NATS server is configured to verify client certificate
	KeyFile *string `pulumi:"keyFile"`
	// The key file content (in PEM format). Needed when NATS server is configured to verify client certificate
	KeyFileData *string `pulumi:"keyFileData"`
}

// TlsInput is an input type that accepts TlsArgs and TlsOutput values.
// You can construct a concrete instance of `TlsInput` via:
//
//	TlsArgs{...}
type TlsInput interface {
	pulumi.Input

	ToTlsOutput() TlsOutput
	ToTlsOutputWithContext(context.Context) TlsOutput
}

type TlsArgs struct {
	// Path to the server root CA file (in PEM format). Needed when the NATS server has TLS enabled with an unknown root CA
	CaFile pulumi.StringPtrInput `pulumi:"caFile"`
	// The root CA (file) content, in PEM format. Needed when the NATS server has TLS enabled with an unknown root CA
	CaFileData pulumi.StringPtrInput `pulumi:"caFileData"`
	// Path to client cert file (in PEM format). Needed when NATS server is configured to verify client certificate
	CertFile pulumi.StringPtrInput `pulumi:"certFile"`
	// The cert file content (in PEM format). Needed when NATS server is configured to verify client certificate
	CertFileData pulumi.StringPtrInput `pulumi:"certFileData"`
	// Path to client key file (in PEM format). Needed when NATS server is configured to verify client certificate
	KeyFile pulumi.StringPtrInput `pulumi:"keyFile"`
	// The key file content (in PEM format). Needed when NATS server is configured to verify client certificate
	KeyFileData pulumi.StringPtrInput `pulumi:"keyFileData"`
}

func (TlsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Tls)(nil)).Elem()
}

func (i TlsArgs) ToTlsOutput() TlsOutput {
	return i.ToTlsOutputWithContext(context.Background())
}

func (i TlsArgs) ToTlsOutputWithContext(ctx context.Context) TlsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TlsOutput)
}

type TlsOutput struct{ *pulumi.OutputState }

func (TlsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Tls)(nil)).Elem()
}

func (o TlsOutput) ToTlsOutput() TlsOutput {
	return o
}

func (o TlsOutput) ToTlsOutputWithContext(ctx context.Context) TlsOutput {
	return o
}

// Path to the server root CA file (in PEM format). Needed when the NATS server has TLS enabled with an unknown root CA
func (o TlsOutput) CaFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Tls) *string { return v.CaFile }).(pulumi.StringPtrOutput)
}

// The root CA (file) content, in PEM format. Needed when the NATS server has TLS enabled with an unknown root CA
func (o TlsOutput) CaFileData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Tls) *string { return v.CaFileData }).(pulumi.StringPtrOutput)
}

// Path to client cert file (in PEM format). Needed when NATS server is configured to verify client certificate
func (o TlsOutput) CertFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Tls) *string { return v.CertFile }).(pulumi.StringPtrOutput)
}

// The cert file content (in PEM format). Needed when NATS server is configured to verify client certificate
func (o TlsOutput) CertFileData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Tls) *string { return v.CertFileData }).(pulumi.StringPtrOutput)
}

// Path to client key file (in PEM format). Needed when NATS server is configured to verify client certificate
func (o TlsOutput) KeyFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Tls) *string { return v.KeyFile }).(pulumi.StringPtrOutput)
}

// The key file content (in PEM format). Needed when NATS server is configured to verify client certificate
func (o TlsOutput) KeyFileData() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Tls) *string { return v.KeyFileData }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TlsInput)(nil)).Elem(), TlsArgs{})
	pulumi.RegisterOutputType(TlsOutput{})
}
