// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Jetstream.Inputs
{

    public sealed class ProviderTlsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path to the server root CA file (in PEM format). Needed when the NATS server has TLS enabled with an unknown root CA
        /// </summary>
        [Input("caFile")]
        public Input<string>? CaFile { get; set; }

        /// <summary>
        /// The root CA (file) content, in PEM format. Needed when the NATS server has TLS enabled with an unknown root CA
        /// </summary>
        [Input("caFileData")]
        public Input<string>? CaFileData { get; set; }

        /// <summary>
        /// Path to client cert file (in PEM format). Needed when NATS server is configured to verify client certificate
        /// </summary>
        [Input("certFile")]
        public Input<string>? CertFile { get; set; }

        /// <summary>
        /// The cert file content (in PEM format). Needed when NATS server is configured to verify client certificate
        /// </summary>
        [Input("certFileData")]
        public Input<string>? CertFileData { get; set; }

        /// <summary>
        /// Path to client key file (in PEM format). Needed when NATS server is configured to verify client certificate
        /// </summary>
        [Input("keyFile")]
        public Input<string>? KeyFile { get; set; }

        /// <summary>
        /// The key file content (in PEM format). Needed when NATS server is configured to verify client certificate
        /// </summary>
        [Input("keyFileData")]
        public Input<string>? KeyFileData { get; set; }

        public ProviderTlsArgs()
        {
        }
        public static new ProviderTlsArgs Empty => new ProviderTlsArgs();
    }
}
